---
- name: Install dan Start Nginx
  hosts: managed_nodes
  become: true

  tasks:
    - name: Matikan unattended-upgrades sementara
      systemd:
        name: unattended-upgrades
        state: stopped
      failed_when: false   # ← tidak error kalau service tidak ada

    - name: Tunggu apt lock bebas
      shell: |
        while fuser /var/lib/dpkg/lock-frontend /var/lib/apt/lists/lock /var/cache/apt/archives/lock >/dev/null 2>&1; do
          echo "Menunggu apt lock..."
          sleep 3
        done
      changed_when: false

    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Nyalakan kembali unattended-upgrades
      systemd:
        name: unattended-upgrades
        state: started
      failed_when: false

    - name: Pastikan nginx running dan enable autostart
      systemd:
        name: nginx
        state: started
        enabled: true

    - name: Cek versi nginx
      command: nginx -v
      register: nginx_version
      changed_when: false

    - name: Tampilkan versi nginx
      debug:
        msg: "{{ nginx_version.stderr }}"