---
- name: Set Timezone ke Asia/Jakarta
  hosts: managed_nodes
  become: true

  tasks:
    - name: Set timezone
      timezone:
        name: "{{ timezone }}"

    - name: Cek timezone aktif
      command: timedatectl show --property=Timezone --value
      register: tz_check
      changed_when: false

    - name: Tampilkan timezone
      debug:
        msg: "Timezone sekarang: {{ tz_check.stdout }}"
